//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int ID { get; set; }
        public string User_Type { get; set; }
        public string User_NO { get; set; }
        public string User_ID { get; set; }
        public string User_AD_ID { get; set; }
        public string User_Pwd { get; set; }
        public string User_CivilizID { get; set; }
        public string User_GroupID { get; set; }
        public string User_CnName { get; set; }
        public string User_EnName { get; set; }
        public string User_Birthday { get; set; }
        public string User_SectionID { get; set; }
        public Nullable<System.DateTime> Ins_DateTime { get; set; }
        public string Ins_UserID { get; set; }
        public Nullable<System.DateTime> Mdy_DateTime { get; set; }
        public string Mdy_UserID { get; set; }
        public string REMK { get; set; }
    }
}
